// Generated by jextract

package opencl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _cl_ndrange {
 *     size_t work_dim;
 *     size_t global_work_offset[3];
 *     size_t global_work_size[3];
 *     size_t local_work_size[3];
 * } cl_ndrange
 * }
 */
public class cl_ndrange extends _cl_ndrange {

    cl_ndrange() {
        // Should not be called directly
    }
}

