// Generated by jextract

package opencl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct fattributiontag {
 *     unsigned int ft_flags;
 *     unsigned long long ft_hash;
 *     char ft_attribution_name[255];
 * } fattributiontag_t
 * }
 */
public class fattributiontag_t extends fattributiontag {

    fattributiontag_t() {
        // Should not be called directly
    }
}

