// Generated by jextract

package opencl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct fchecklv {
 *     off_t lv_file_start;
 *     size_t lv_error_message_size;
 *     void *lv_error_message;
 * } fchecklv_t
 * }
 */
public class fchecklv_t extends fchecklv {

    fchecklv_t() {
        // Should not be called directly
    }
}

