// Generated by jextract

package opencl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct fgetsigsinfo {
 *     off_t fg_file_start;
 *     int fg_info_request;
 *     int fg_sig_is_platform;
 * } fgetsigsinfo_t
 * }
 */
public class fgetsigsinfo_t extends fgetsigsinfo {

    fgetsigsinfo_t() {
        // Should not be called directly
    }
}

