// Generated by jextract

package opencl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct flocktimeout {
 *     struct flock fl;
 *     struct timespec timeout;
 * }
 * }
 */
public class flocktimeout {

    flocktimeout() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        flock.layout().withName("fl"),
        timespec.layout().withName("timeout")
    ).withName("flocktimeout");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout fl$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("fl"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct flock fl
     * }
     */
    public static final GroupLayout fl$layout() {
        return fl$LAYOUT;
    }

    private static final long fl$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct flock fl
     * }
     */
    public static final long fl$offset() {
        return fl$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct flock fl
     * }
     */
    public static MemorySegment fl(MemorySegment struct) {
        return struct.asSlice(fl$OFFSET, fl$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct flock fl
     * }
     */
    public static void fl(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, fl$OFFSET, fl$LAYOUT.byteSize());
    }

    private static final GroupLayout timeout$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("timeout"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct timespec timeout
     * }
     */
    public static final GroupLayout timeout$layout() {
        return timeout$LAYOUT;
    }

    private static final long timeout$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct timespec timeout
     * }
     */
    public static final long timeout$offset() {
        return timeout$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct timespec timeout
     * }
     */
    public static MemorySegment timeout(MemorySegment struct) {
        return struct.asSlice(timeout$OFFSET, timeout$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct timespec timeout
     * }
     */
    public static void timeout(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, timeout$OFFSET, timeout$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

