// Generated by jextract

package opencl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct fpunchhole {
 *     unsigned int fp_flags;
 *     unsigned int reserved;
 *     off_t fp_offset;
 *     off_t fp_length;
 * } fpunchhole_t
 * }
 */
public class fpunchhole_t extends fpunchhole {

    fpunchhole_t() {
        // Should not be called directly
    }
}

