// Generated by jextract

package opencl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct fsignatures {
 *     off_t fs_file_start;
 *     void *fs_blob_start;
 *     size_t fs_blob_size;
 *     size_t fs_fsignatures_size;
 *     char fs_cdhash[20];
 *     int fs_hash_type;
 * } fsignatures_t
 * }
 */
public class fsignatures_t extends fsignatures {

    fsignatures_t() {
        // Should not be called directly
    }
}

