// Generated by jextract

package opencl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct fspecread {
 *     unsigned int fsr_flags;
 *     unsigned int reserved;
 *     off_t fsr_offset;
 *     off_t fsr_length;
 * } fspecread_t
 * }
 */
public class fspecread_t extends fspecread {

    fspecread_t() {
        // Should not be called directly
    }
}

