// Generated by jextract

package opencl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct fstore {
 *     unsigned int fst_flags;
 *     int fst_posmode;
 *     off_t fst_offset;
 *     off_t fst_length;
 *     off_t fst_bytesalloc;
 * } fstore_t
 * }
 */
public class fstore_t extends fstore {

    fstore_t() {
        // Should not be called directly
    }
}

