// Generated by jextract

package opencl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct fsupplement {
 *     off_t fs_file_start;
 *     off_t fs_blob_start;
 *     size_t fs_blob_size;
 *     int fs_orig_fd;
 * } fsupplement_t
 * }
 */
public class fsupplement_t extends fsupplement {

    fsupplement_t() {
        // Should not be called directly
    }
}

