// Generated by jextract

package opencl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct ftrimactivefile {
 *     off_t fta_offset;
 *     off_t fta_length;
 * } ftrimactivefile_t
 * }
 */
public class ftrimactivefile_t extends ftrimactivefile {

    ftrimactivefile_t() {
        // Should not be called directly
    }
}

