// Generated by jextract

package opencl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class opencl_h extends opencl_h_1 {

    opencl_h() {
        // Should not be called directly
    }
    private static final int NBBY = (int)8L;
    /**
     * {@snippet lang=c :
     * #define NBBY 8
     * }
     */
    public static int NBBY() {
        return NBBY;
    }
    private static final long NFDBITS = 32L;
    /**
     * {@snippet lang=c :
     * #define NFDBITS 32
     * }
     */
    public static long NFDBITS() {
        return NFDBITS;
    }
    private static final int FD_SETSIZE = (int)1024L;
    /**
     * {@snippet lang=c :
     * #define FD_SETSIZE 1024
     * }
     */
    public static int FD_SETSIZE() {
        return FD_SETSIZE;
    }
    private static final int __DARWIN_WCHAR_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define __DARWIN_WCHAR_MAX 2147483647
     * }
     */
    public static int __DARWIN_WCHAR_MAX() {
        return __DARWIN_WCHAR_MAX;
    }
    private static final int __DARWIN_WCHAR_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define __DARWIN_WCHAR_MIN -2147483648
     * }
     */
    public static int __DARWIN_WCHAR_MIN() {
        return __DARWIN_WCHAR_MIN;
    }
    private static final int __DARWIN_WEOF = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define __DARWIN_WEOF -1
     * }
     */
    public static int __DARWIN_WEOF() {
        return __DARWIN_WEOF;
    }
    private static final long _POSIX_VERSION = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_VERSION 200112
     * }
     */
    public static long _POSIX_VERSION() {
        return _POSIX_VERSION;
    }
    private static final long _POSIX2_VERSION = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_VERSION 200112
     * }
     */
    public static long _POSIX2_VERSION() {
        return _POSIX2_VERSION;
    }
    private static final byte _POSIX_VDISABLE = (byte)255L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_VDISABLE 255
     * }
     */
    public static byte _POSIX_VDISABLE() {
        return _POSIX_VDISABLE;
    }
    private static final int X_OK = (int)1L;
    /**
     * {@snippet lang=c :
     * #define X_OK 1
     * }
     */
    public static int X_OK() {
        return X_OK;
    }
    private static final int W_OK = (int)2L;
    /**
     * {@snippet lang=c :
     * #define W_OK 2
     * }
     */
    public static int W_OK() {
        return W_OK;
    }
    private static final int R_OK = (int)4L;
    /**
     * {@snippet lang=c :
     * #define R_OK 4
     * }
     */
    public static int R_OK() {
        return R_OK;
    }
    private static final int _READ_OK = (int)512L;
    /**
     * {@snippet lang=c :
     * #define _READ_OK 512
     * }
     */
    public static int _READ_OK() {
        return _READ_OK;
    }
    private static final int _WRITE_OK = (int)1024L;
    /**
     * {@snippet lang=c :
     * #define _WRITE_OK 1024
     * }
     */
    public static int _WRITE_OK() {
        return _WRITE_OK;
    }
    private static final int _EXECUTE_OK = (int)2048L;
    /**
     * {@snippet lang=c :
     * #define _EXECUTE_OK 2048
     * }
     */
    public static int _EXECUTE_OK() {
        return _EXECUTE_OK;
    }
    private static final int _DELETE_OK = (int)4096L;
    /**
     * {@snippet lang=c :
     * #define _DELETE_OK 4096
     * }
     */
    public static int _DELETE_OK() {
        return _DELETE_OK;
    }
    private static final int _APPEND_OK = (int)8192L;
    /**
     * {@snippet lang=c :
     * #define _APPEND_OK 8192
     * }
     */
    public static int _APPEND_OK() {
        return _APPEND_OK;
    }
    private static final int _RMFILE_OK = (int)16384L;
    /**
     * {@snippet lang=c :
     * #define _RMFILE_OK 16384
     * }
     */
    public static int _RMFILE_OK() {
        return _RMFILE_OK;
    }
    private static final int _RATTR_OK = (int)32768L;
    /**
     * {@snippet lang=c :
     * #define _RATTR_OK 32768
     * }
     */
    public static int _RATTR_OK() {
        return _RATTR_OK;
    }
    private static final int _WATTR_OK = (int)65536L;
    /**
     * {@snippet lang=c :
     * #define _WATTR_OK 65536
     * }
     */
    public static int _WATTR_OK() {
        return _WATTR_OK;
    }
    private static final int _REXT_OK = (int)131072L;
    /**
     * {@snippet lang=c :
     * #define _REXT_OK 131072
     * }
     */
    public static int _REXT_OK() {
        return _REXT_OK;
    }
    private static final int _WEXT_OK = (int)262144L;
    /**
     * {@snippet lang=c :
     * #define _WEXT_OK 262144
     * }
     */
    public static int _WEXT_OK() {
        return _WEXT_OK;
    }
    private static final int _RPERM_OK = (int)524288L;
    /**
     * {@snippet lang=c :
     * #define _RPERM_OK 524288
     * }
     */
    public static int _RPERM_OK() {
        return _RPERM_OK;
    }
    private static final int _WPERM_OK = (int)1048576L;
    /**
     * {@snippet lang=c :
     * #define _WPERM_OK 1048576
     * }
     */
    public static int _WPERM_OK() {
        return _WPERM_OK;
    }
    private static final int _CHOWN_OK = (int)2097152L;
    /**
     * {@snippet lang=c :
     * #define _CHOWN_OK 2097152
     * }
     */
    public static int _CHOWN_OK() {
        return _CHOWN_OK;
    }
    private static final int _ACCESS_EXTENDED_MASK = (int)4193792L;
    /**
     * {@snippet lang=c :
     * #define _ACCESS_EXTENDED_MASK 4193792
     * }
     */
    public static int _ACCESS_EXTENDED_MASK() {
        return _ACCESS_EXTENDED_MASK;
    }
    private static final int L_SET = (int)0L;
    /**
     * {@snippet lang=c :
     * #define L_SET 0
     * }
     */
    public static int L_SET() {
        return L_SET;
    }
    private static final int L_INCR = (int)1L;
    /**
     * {@snippet lang=c :
     * #define L_INCR 1
     * }
     */
    public static int L_INCR() {
        return L_INCR;
    }
    private static final int L_XTND = (int)2L;
    /**
     * {@snippet lang=c :
     * #define L_XTND 2
     * }
     */
    public static int L_XTND() {
        return L_XTND;
    }
    private static final int ACCESSX_MAX_TABLESIZE = (int)16384L;
    /**
     * {@snippet lang=c :
     * #define ACCESSX_MAX_TABLESIZE 16384
     * }
     */
    public static int ACCESSX_MAX_TABLESIZE() {
        return ACCESSX_MAX_TABLESIZE;
    }
    private static final int _POSIX_ADVISORY_INFO = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_ADVISORY_INFO -1
     * }
     */
    public static int _POSIX_ADVISORY_INFO() {
        return _POSIX_ADVISORY_INFO;
    }
    private static final int _POSIX_ASYNCHRONOUS_IO = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_ASYNCHRONOUS_IO -1
     * }
     */
    public static int _POSIX_ASYNCHRONOUS_IO() {
        return _POSIX_ASYNCHRONOUS_IO;
    }
    private static final int _POSIX_BARRIERS = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_BARRIERS -1
     * }
     */
    public static int _POSIX_BARRIERS() {
        return _POSIX_BARRIERS;
    }
    private static final long _POSIX_CHOWN_RESTRICTED = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_CHOWN_RESTRICTED 200112
     * }
     */
    public static long _POSIX_CHOWN_RESTRICTED() {
        return _POSIX_CHOWN_RESTRICTED;
    }
    private static final int _POSIX_CLOCK_SELECTION = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_CLOCK_SELECTION -1
     * }
     */
    public static int _POSIX_CLOCK_SELECTION() {
        return _POSIX_CLOCK_SELECTION;
    }
    private static final int _POSIX_CPUTIME = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_CPUTIME -1
     * }
     */
    public static int _POSIX_CPUTIME() {
        return _POSIX_CPUTIME;
    }
    private static final long _POSIX_FSYNC = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_FSYNC 200112
     * }
     */
    public static long _POSIX_FSYNC() {
        return _POSIX_FSYNC;
    }
    private static final long _POSIX_IPV6 = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_IPV6 200112
     * }
     */
    public static long _POSIX_IPV6() {
        return _POSIX_IPV6;
    }
    private static final long _POSIX_JOB_CONTROL = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_JOB_CONTROL 200112
     * }
     */
    public static long _POSIX_JOB_CONTROL() {
        return _POSIX_JOB_CONTROL;
    }
    private static final long _POSIX_MAPPED_FILES = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_MAPPED_FILES 200112
     * }
     */
    public static long _POSIX_MAPPED_FILES() {
        return _POSIX_MAPPED_FILES;
    }
    private static final int _POSIX_MEMLOCK = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_MEMLOCK -1
     * }
     */
    public static int _POSIX_MEMLOCK() {
        return _POSIX_MEMLOCK;
    }
    private static final int _POSIX_MEMLOCK_RANGE = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_MEMLOCK_RANGE -1
     * }
     */
    public static int _POSIX_MEMLOCK_RANGE() {
        return _POSIX_MEMLOCK_RANGE;
    }
    private static final long _POSIX_MEMORY_PROTECTION = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_MEMORY_PROTECTION 200112
     * }
     */
    public static long _POSIX_MEMORY_PROTECTION() {
        return _POSIX_MEMORY_PROTECTION;
    }
    private static final int _POSIX_MESSAGE_PASSING = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_MESSAGE_PASSING -1
     * }
     */
    public static int _POSIX_MESSAGE_PASSING() {
        return _POSIX_MESSAGE_PASSING;
    }
    private static final int _POSIX_MONOTONIC_CLOCK = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_MONOTONIC_CLOCK -1
     * }
     */
    public static int _POSIX_MONOTONIC_CLOCK() {
        return _POSIX_MONOTONIC_CLOCK;
    }
    private static final long _POSIX_NO_TRUNC = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_NO_TRUNC 200112
     * }
     */
    public static long _POSIX_NO_TRUNC() {
        return _POSIX_NO_TRUNC;
    }
    private static final int _POSIX_PRIORITIZED_IO = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_PRIORITIZED_IO -1
     * }
     */
    public static int _POSIX_PRIORITIZED_IO() {
        return _POSIX_PRIORITIZED_IO;
    }
    private static final int _POSIX_PRIORITY_SCHEDULING = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_PRIORITY_SCHEDULING -1
     * }
     */
    public static int _POSIX_PRIORITY_SCHEDULING() {
        return _POSIX_PRIORITY_SCHEDULING;
    }
    private static final int _POSIX_RAW_SOCKETS = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_RAW_SOCKETS -1
     * }
     */
    public static int _POSIX_RAW_SOCKETS() {
        return _POSIX_RAW_SOCKETS;
    }
    private static final long _POSIX_READER_WRITER_LOCKS = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_READER_WRITER_LOCKS 200112
     * }
     */
    public static long _POSIX_READER_WRITER_LOCKS() {
        return _POSIX_READER_WRITER_LOCKS;
    }
    private static final int _POSIX_REALTIME_SIGNALS = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_REALTIME_SIGNALS -1
     * }
     */
    public static int _POSIX_REALTIME_SIGNALS() {
        return _POSIX_REALTIME_SIGNALS;
    }
    private static final long _POSIX_REGEXP = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_REGEXP 200112
     * }
     */
    public static long _POSIX_REGEXP() {
        return _POSIX_REGEXP;
    }
    private static final long _POSIX_SAVED_IDS = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_SAVED_IDS 200112
     * }
     */
    public static long _POSIX_SAVED_IDS() {
        return _POSIX_SAVED_IDS;
    }
    private static final int _POSIX_SEMAPHORES = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_SEMAPHORES -1
     * }
     */
    public static int _POSIX_SEMAPHORES() {
        return _POSIX_SEMAPHORES;
    }
    private static final int _POSIX_SHARED_MEMORY_OBJECTS = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_SHARED_MEMORY_OBJECTS -1
     * }
     */
    public static int _POSIX_SHARED_MEMORY_OBJECTS() {
        return _POSIX_SHARED_MEMORY_OBJECTS;
    }
    private static final long _POSIX_SHELL = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_SHELL 200112
     * }
     */
    public static long _POSIX_SHELL() {
        return _POSIX_SHELL;
    }
    private static final long _POSIX_SPAWN = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_SPAWN 200112
     * }
     */
    public static long _POSIX_SPAWN() {
        return _POSIX_SPAWN;
    }
    private static final int _POSIX_SPIN_LOCKS = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_SPIN_LOCKS -1
     * }
     */
    public static int _POSIX_SPIN_LOCKS() {
        return _POSIX_SPIN_LOCKS;
    }
    private static final int _POSIX_SPORADIC_SERVER = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_SPORADIC_SERVER -1
     * }
     */
    public static int _POSIX_SPORADIC_SERVER() {
        return _POSIX_SPORADIC_SERVER;
    }
    private static final int _POSIX_SYNCHRONIZED_IO = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_SYNCHRONIZED_IO -1
     * }
     */
    public static int _POSIX_SYNCHRONIZED_IO() {
        return _POSIX_SYNCHRONIZED_IO;
    }
    private static final long _POSIX_THREAD_ATTR_STACKADDR = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_THREAD_ATTR_STACKADDR 200112
     * }
     */
    public static long _POSIX_THREAD_ATTR_STACKADDR() {
        return _POSIX_THREAD_ATTR_STACKADDR;
    }
    private static final long _POSIX_THREAD_ATTR_STACKSIZE = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_THREAD_ATTR_STACKSIZE 200112
     * }
     */
    public static long _POSIX_THREAD_ATTR_STACKSIZE() {
        return _POSIX_THREAD_ATTR_STACKSIZE;
    }
    private static final int _POSIX_THREAD_CPUTIME = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_THREAD_CPUTIME -1
     * }
     */
    public static int _POSIX_THREAD_CPUTIME() {
        return _POSIX_THREAD_CPUTIME;
    }
    private static final int _POSIX_THREAD_PRIO_INHERIT = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_THREAD_PRIO_INHERIT -1
     * }
     */
    public static int _POSIX_THREAD_PRIO_INHERIT() {
        return _POSIX_THREAD_PRIO_INHERIT;
    }
    private static final int _POSIX_THREAD_PRIO_PROTECT = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_THREAD_PRIO_PROTECT -1
     * }
     */
    public static int _POSIX_THREAD_PRIO_PROTECT() {
        return _POSIX_THREAD_PRIO_PROTECT;
    }
    private static final int _POSIX_THREAD_PRIORITY_SCHEDULING = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_THREAD_PRIORITY_SCHEDULING -1
     * }
     */
    public static int _POSIX_THREAD_PRIORITY_SCHEDULING() {
        return _POSIX_THREAD_PRIORITY_SCHEDULING;
    }
    private static final long _POSIX_THREAD_PROCESS_SHARED = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_THREAD_PROCESS_SHARED 200112
     * }
     */
    public static long _POSIX_THREAD_PROCESS_SHARED() {
        return _POSIX_THREAD_PROCESS_SHARED;
    }
    private static final long _POSIX_THREAD_SAFE_FUNCTIONS = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_THREAD_SAFE_FUNCTIONS 200112
     * }
     */
    public static long _POSIX_THREAD_SAFE_FUNCTIONS() {
        return _POSIX_THREAD_SAFE_FUNCTIONS;
    }
    private static final int _POSIX_THREAD_SPORADIC_SERVER = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_THREAD_SPORADIC_SERVER -1
     * }
     */
    public static int _POSIX_THREAD_SPORADIC_SERVER() {
        return _POSIX_THREAD_SPORADIC_SERVER;
    }
    private static final long _POSIX_THREADS = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_THREADS 200112
     * }
     */
    public static long _POSIX_THREADS() {
        return _POSIX_THREADS;
    }
    private static final int _POSIX_TIMEOUTS = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_TIMEOUTS -1
     * }
     */
    public static int _POSIX_TIMEOUTS() {
        return _POSIX_TIMEOUTS;
    }
    private static final int _POSIX_TIMERS = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_TIMERS -1
     * }
     */
    public static int _POSIX_TIMERS() {
        return _POSIX_TIMERS;
    }
    private static final int _POSIX_TRACE = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_TRACE -1
     * }
     */
    public static int _POSIX_TRACE() {
        return _POSIX_TRACE;
    }
    private static final int _POSIX_TRACE_EVENT_FILTER = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_TRACE_EVENT_FILTER -1
     * }
     */
    public static int _POSIX_TRACE_EVENT_FILTER() {
        return _POSIX_TRACE_EVENT_FILTER;
    }
    private static final int _POSIX_TRACE_INHERIT = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_TRACE_INHERIT -1
     * }
     */
    public static int _POSIX_TRACE_INHERIT() {
        return _POSIX_TRACE_INHERIT;
    }
    private static final int _POSIX_TRACE_LOG = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_TRACE_LOG -1
     * }
     */
    public static int _POSIX_TRACE_LOG() {
        return _POSIX_TRACE_LOG;
    }
    private static final int _POSIX_TYPED_MEMORY_OBJECTS = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_TYPED_MEMORY_OBJECTS -1
     * }
     */
    public static int _POSIX_TYPED_MEMORY_OBJECTS() {
        return _POSIX_TYPED_MEMORY_OBJECTS;
    }
    private static final long _POSIX2_C_BIND = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_C_BIND 200112
     * }
     */
    public static long _POSIX2_C_BIND() {
        return _POSIX2_C_BIND;
    }
    private static final long _POSIX2_C_DEV = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_C_DEV 200112
     * }
     */
    public static long _POSIX2_C_DEV() {
        return _POSIX2_C_DEV;
    }
    private static final long _POSIX2_CHAR_TERM = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_CHAR_TERM 200112
     * }
     */
    public static long _POSIX2_CHAR_TERM() {
        return _POSIX2_CHAR_TERM;
    }
    private static final int _POSIX2_FORT_DEV = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_FORT_DEV -1
     * }
     */
    public static int _POSIX2_FORT_DEV() {
        return _POSIX2_FORT_DEV;
    }
    private static final long _POSIX2_FORT_RUN = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_FORT_RUN 200112
     * }
     */
    public static long _POSIX2_FORT_RUN() {
        return _POSIX2_FORT_RUN;
    }
    private static final long _POSIX2_LOCALEDEF = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_LOCALEDEF 200112
     * }
     */
    public static long _POSIX2_LOCALEDEF() {
        return _POSIX2_LOCALEDEF;
    }
    private static final int _POSIX2_PBS = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_PBS -1
     * }
     */
    public static int _POSIX2_PBS() {
        return _POSIX2_PBS;
    }
    private static final int _POSIX2_PBS_ACCOUNTING = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_PBS_ACCOUNTING -1
     * }
     */
    public static int _POSIX2_PBS_ACCOUNTING() {
        return _POSIX2_PBS_ACCOUNTING;
    }
    private static final int _POSIX2_PBS_CHECKPOINT = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_PBS_CHECKPOINT -1
     * }
     */
    public static int _POSIX2_PBS_CHECKPOINT() {
        return _POSIX2_PBS_CHECKPOINT;
    }
    private static final int _POSIX2_PBS_LOCATE = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_PBS_LOCATE -1
     * }
     */
    public static int _POSIX2_PBS_LOCATE() {
        return _POSIX2_PBS_LOCATE;
    }
    private static final int _POSIX2_PBS_MESSAGE = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_PBS_MESSAGE -1
     * }
     */
    public static int _POSIX2_PBS_MESSAGE() {
        return _POSIX2_PBS_MESSAGE;
    }
    private static final int _POSIX2_PBS_TRACK = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_PBS_TRACK -1
     * }
     */
    public static int _POSIX2_PBS_TRACK() {
        return _POSIX2_PBS_TRACK;
    }
    private static final long _POSIX2_SW_DEV = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_SW_DEV 200112
     * }
     */
    public static long _POSIX2_SW_DEV() {
        return _POSIX2_SW_DEV;
    }
    private static final long _POSIX2_UPE = 200112L;
    /**
     * {@snippet lang=c :
     * #define _POSIX2_UPE 200112
     * }
     */
    public static long _POSIX2_UPE() {
        return _POSIX2_UPE;
    }
    private static final int __ILP32_OFF32 = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define __ILP32_OFF32 -1
     * }
     */
    public static int __ILP32_OFF32() {
        return __ILP32_OFF32;
    }
    private static final int __ILP32_OFFBIG = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define __ILP32_OFFBIG -1
     * }
     */
    public static int __ILP32_OFFBIG() {
        return __ILP32_OFFBIG;
    }
    private static final int __LP64_OFF64 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __LP64_OFF64 1
     * }
     */
    public static int __LP64_OFF64() {
        return __LP64_OFF64;
    }
    private static final int __LPBIG_OFFBIG = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __LPBIG_OFFBIG 1
     * }
     */
    public static int __LPBIG_OFFBIG() {
        return __LPBIG_OFFBIG;
    }
    private static final int _POSIX_V6_ILP32_OFF32 = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_V6_ILP32_OFF32 -1
     * }
     */
    public static int _POSIX_V6_ILP32_OFF32() {
        return _POSIX_V6_ILP32_OFF32;
    }
    private static final int _POSIX_V6_ILP32_OFFBIG = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_V6_ILP32_OFFBIG -1
     * }
     */
    public static int _POSIX_V6_ILP32_OFFBIG() {
        return _POSIX_V6_ILP32_OFFBIG;
    }
    private static final int _POSIX_V6_LP64_OFF64 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_V6_LP64_OFF64 1
     * }
     */
    public static int _POSIX_V6_LP64_OFF64() {
        return _POSIX_V6_LP64_OFF64;
    }
    private static final int _POSIX_V6_LPBIG_OFFBIG = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_V6_LPBIG_OFFBIG 1
     * }
     */
    public static int _POSIX_V6_LPBIG_OFFBIG() {
        return _POSIX_V6_LPBIG_OFFBIG;
    }
    private static final int _POSIX_V7_ILP32_OFF32 = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_V7_ILP32_OFF32 -1
     * }
     */
    public static int _POSIX_V7_ILP32_OFF32() {
        return _POSIX_V7_ILP32_OFF32;
    }
    private static final int _POSIX_V7_ILP32_OFFBIG = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_V7_ILP32_OFFBIG -1
     * }
     */
    public static int _POSIX_V7_ILP32_OFFBIG() {
        return _POSIX_V7_ILP32_OFFBIG;
    }
    private static final int _POSIX_V7_LP64_OFF64 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_V7_LP64_OFF64 1
     * }
     */
    public static int _POSIX_V7_LP64_OFF64() {
        return _POSIX_V7_LP64_OFF64;
    }
    private static final int _POSIX_V7_LPBIG_OFFBIG = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _POSIX_V7_LPBIG_OFFBIG 1
     * }
     */
    public static int _POSIX_V7_LPBIG_OFFBIG() {
        return _POSIX_V7_LPBIG_OFFBIG;
    }
    private static final int _V6_ILP32_OFF32 = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _V6_ILP32_OFF32 -1
     * }
     */
    public static int _V6_ILP32_OFF32() {
        return _V6_ILP32_OFF32;
    }
    private static final int _V6_ILP32_OFFBIG = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _V6_ILP32_OFFBIG -1
     * }
     */
    public static int _V6_ILP32_OFFBIG() {
        return _V6_ILP32_OFFBIG;
    }
    private static final int _V6_LP64_OFF64 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _V6_LP64_OFF64 1
     * }
     */
    public static int _V6_LP64_OFF64() {
        return _V6_LP64_OFF64;
    }
    private static final int _V6_LPBIG_OFFBIG = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _V6_LPBIG_OFFBIG 1
     * }
     */
    public static int _V6_LPBIG_OFFBIG() {
        return _V6_LPBIG_OFFBIG;
    }
    private static final int _XBS5_ILP32_OFF32 = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _XBS5_ILP32_OFF32 -1
     * }
     */
    public static int _XBS5_ILP32_OFF32() {
        return _XBS5_ILP32_OFF32;
    }
    private static final int _XBS5_ILP32_OFFBIG = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _XBS5_ILP32_OFFBIG -1
     * }
     */
    public static int _XBS5_ILP32_OFFBIG() {
        return _XBS5_ILP32_OFFBIG;
    }
    private static final int _XBS5_LP64_OFF64 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _XBS5_LP64_OFF64 1
     * }
     */
    public static int _XBS5_LP64_OFF64() {
        return _XBS5_LP64_OFF64;
    }
    private static final int _XBS5_LPBIG_OFFBIG = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _XBS5_LPBIG_OFFBIG 1
     * }
     */
    public static int _XBS5_LPBIG_OFFBIG() {
        return _XBS5_LPBIG_OFFBIG;
    }
    private static final int _XOPEN_CRYPT = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _XOPEN_CRYPT 1
     * }
     */
    public static int _XOPEN_CRYPT() {
        return _XOPEN_CRYPT;
    }
    private static final int _XOPEN_ENH_I18N = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _XOPEN_ENH_I18N 1
     * }
     */
    public static int _XOPEN_ENH_I18N() {
        return _XOPEN_ENH_I18N;
    }
    private static final int _XOPEN_LEGACY = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _XOPEN_LEGACY -1
     * }
     */
    public static int _XOPEN_LEGACY() {
        return _XOPEN_LEGACY;
    }
    private static final int _XOPEN_REALTIME = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _XOPEN_REALTIME -1
     * }
     */
    public static int _XOPEN_REALTIME() {
        return _XOPEN_REALTIME;
    }
    private static final int _XOPEN_REALTIME_THREADS = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _XOPEN_REALTIME_THREADS -1
     * }
     */
    public static int _XOPEN_REALTIME_THREADS() {
        return _XOPEN_REALTIME_THREADS;
    }
    private static final int _XOPEN_SHM = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _XOPEN_SHM 1
     * }
     */
    public static int _XOPEN_SHM() {
        return _XOPEN_SHM;
    }
    private static final int _XOPEN_STREAMS = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define _XOPEN_STREAMS -1
     * }
     */
    public static int _XOPEN_STREAMS() {
        return _XOPEN_STREAMS;
    }
    private static final int _XOPEN_UNIX = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _XOPEN_UNIX 1
     * }
     */
    public static int _XOPEN_UNIX() {
        return _XOPEN_UNIX;
    }
    private static final int _SC_PAGE_SIZE = (int)29L;
    /**
     * {@snippet lang=c :
     * #define _SC_PAGE_SIZE 29
     * }
     */
    public static int _SC_PAGE_SIZE() {
        return _SC_PAGE_SIZE;
    }
    private static final int O_FSYNC = (int)128L;
    /**
     * {@snippet lang=c :
     * #define O_FSYNC 128
     * }
     */
    public static int O_FSYNC() {
        return O_FSYNC;
    }
    private static final int O_SEARCH = (int)1074790400L;
    /**
     * {@snippet lang=c :
     * #define O_SEARCH 1074790400
     * }
     */
    public static int O_SEARCH() {
        return O_SEARCH;
    }
    private static final int AT_FDCWD = (int)-2L;
    /**
     * {@snippet lang=c :
     * #define AT_FDCWD -2
     * }
     */
    public static int AT_FDCWD() {
        return AT_FDCWD;
    }
    private static final int AUTH_OPEN_NOAUTHFD = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define AUTH_OPEN_NOAUTHFD -1
     * }
     */
    public static int AUTH_OPEN_NOAUTHFD() {
        return AUTH_OPEN_NOAUTHFD;
    }
    private static final int FAPPEND = (int)8L;
    /**
     * {@snippet lang=c :
     * #define FAPPEND 8
     * }
     */
    public static int FAPPEND() {
        return FAPPEND;
    }
    private static final int FASYNC = (int)64L;
    /**
     * {@snippet lang=c :
     * #define FASYNC 64
     * }
     */
    public static int FASYNC() {
        return FASYNC;
    }
    private static final int FFSYNC = (int)128L;
    /**
     * {@snippet lang=c :
     * #define FFSYNC 128
     * }
     */
    public static int FFSYNC() {
        return FFSYNC;
    }
    private static final int FFDSYNC = (int)4194304L;
    /**
     * {@snippet lang=c :
     * #define FFDSYNC 4194304
     * }
     */
    public static int FFDSYNC() {
        return FFDSYNC;
    }
    private static final int FNONBLOCK = (int)4L;
    /**
     * {@snippet lang=c :
     * #define FNONBLOCK 4
     * }
     */
    public static int FNONBLOCK() {
        return FNONBLOCK;
    }
    private static final int FNDELAY = (int)4L;
    /**
     * {@snippet lang=c :
     * #define FNDELAY 4
     * }
     */
    public static int FNDELAY() {
        return FNDELAY;
    }
    private static final int O_NDELAY = (int)4L;
    /**
     * {@snippet lang=c :
     * #define O_NDELAY 4
     * }
     */
    public static int O_NDELAY() {
        return O_NDELAY;
    }
    private static final int CPF_MASK = (int)3L;
    /**
     * {@snippet lang=c :
     * #define CPF_MASK 3
     * }
     */
    public static int CPF_MASK() {
        return CPF_MASK;
    }
    private static final int S_ISTXT = (int)512L;
    /**
     * {@snippet lang=c :
     * #define S_ISTXT 512
     * }
     */
    public static int S_ISTXT() {
        return S_ISTXT;
    }
    private static final int S_IREAD = (int)256L;
    /**
     * {@snippet lang=c :
     * #define S_IREAD 256
     * }
     */
    public static int S_IREAD() {
        return S_IREAD;
    }
    private static final int S_IWRITE = (int)128L;
    /**
     * {@snippet lang=c :
     * #define S_IWRITE 128
     * }
     */
    public static int S_IWRITE() {
        return S_IWRITE;
    }
    private static final int S_IEXEC = (int)64L;
    /**
     * {@snippet lang=c :
     * #define S_IEXEC 64
     * }
     */
    public static int S_IEXEC() {
        return S_IEXEC;
    }
    private static final int O_POPUP = (int)2147483648L;
    /**
     * {@snippet lang=c :
     * #define O_POPUP 2147483648
     * }
     */
    public static int O_POPUP() {
        return O_POPUP;
    }
    private static final int FILESEC_GUID = (int)3L;
    /**
     * {@snippet lang=c :
     * #define FILESEC_GUID 3
     * }
     */
    public static int FILESEC_GUID() {
        return FILESEC_GUID;
    }
    private static final MemorySegment _FILESEC_UNSET_PROPERTY = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define _FILESEC_UNSET_PROPERTY (void*) 0
     * }
     */
    public static MemorySegment _FILESEC_UNSET_PROPERTY() {
        return _FILESEC_UNSET_PROPERTY;
    }
    private static final MemorySegment _FILESEC_REMOVE_ACL = MemorySegment.ofAddress(1L);
    /**
     * {@snippet lang=c :
     * #define _FILESEC_REMOVE_ACL (void*) 1
     * }
     */
    public static MemorySegment _FILESEC_REMOVE_ACL() {
        return _FILESEC_REMOVE_ACL;
    }
    private static final int NSIG = (int)32L;
    /**
     * {@snippet lang=c :
     * #define NSIG 32
     * }
     */
    public static int NSIG() {
        return NSIG;
    }
    private static final int SIGIOT = (int)6L;
    /**
     * {@snippet lang=c :
     * #define SIGIOT 6
     * }
     */
    public static int SIGIOT() {
        return SIGIOT;
    }
    private static final MemorySegment SIG_DFL = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define SIG_DFL (void*) 0
     * }
     */
    public static MemorySegment SIG_DFL() {
        return SIG_DFL;
    }
    private static final MemorySegment SIG_IGN = MemorySegment.ofAddress(1L);
    /**
     * {@snippet lang=c :
     * #define SIG_IGN (void*) 1
     * }
     */
    public static MemorySegment SIG_IGN() {
        return SIG_IGN;
    }
    private static final MemorySegment SIG_HOLD = MemorySegment.ofAddress(5L);
    /**
     * {@snippet lang=c :
     * #define SIG_HOLD (void*) 5
     * }
     */
    public static MemorySegment SIG_HOLD() {
        return SIG_HOLD;
    }
    private static final MemorySegment SIG_ERR = MemorySegment.ofAddress(-1L);
    /**
     * {@snippet lang=c :
     * #define SIG_ERR (void*) -1
     * }
     */
    public static MemorySegment SIG_ERR() {
        return SIG_ERR;
    }
    private static final int SA_USERSPACE_MASK = (int)127L;
    /**
     * {@snippet lang=c :
     * #define SA_USERSPACE_MASK 127
     * }
     */
    public static int SA_USERSPACE_MASK() {
        return SA_USERSPACE_MASK;
    }
    private static final int SV_ONSTACK = (int)1L;
    /**
     * {@snippet lang=c :
     * #define SV_ONSTACK 1
     * }
     */
    public static int SV_ONSTACK() {
        return SV_ONSTACK;
    }
    private static final int SV_INTERRUPT = (int)2L;
    /**
     * {@snippet lang=c :
     * #define SV_INTERRUPT 2
     * }
     */
    public static int SV_INTERRUPT() {
        return SV_INTERRUPT;
    }
    private static final int SV_RESETHAND = (int)4L;
    /**
     * {@snippet lang=c :
     * #define SV_RESETHAND 4
     * }
     */
    public static int SV_RESETHAND() {
        return SV_RESETHAND;
    }
    private static final int SV_NODEFER = (int)16L;
    /**
     * {@snippet lang=c :
     * #define SV_NODEFER 16
     * }
     */
    public static int SV_NODEFER() {
        return SV_NODEFER;
    }
    private static final int SV_NOCLDSTOP = (int)8L;
    /**
     * {@snippet lang=c :
     * #define SV_NOCLDSTOP 8
     * }
     */
    public static int SV_NOCLDSTOP() {
        return SV_NOCLDSTOP;
    }
    private static final int SV_SIGINFO = (int)64L;
    /**
     * {@snippet lang=c :
     * #define SV_SIGINFO 64
     * }
     */
    public static int SV_SIGINFO() {
        return SV_SIGINFO;
    }
    private static final MemorySegment BADSIG = MemorySegment.ofAddress(-1L);
    /**
     * {@snippet lang=c :
     * #define BADSIG (void*) -1
     * }
     */
    public static MemorySegment BADSIG() {
        return BADSIG;
    }
    private static final int PRIO_MIN = (int)-20L;
    /**
     * {@snippet lang=c :
     * #define PRIO_MIN -20
     * }
     */
    public static int PRIO_MIN() {
        return PRIO_MIN;
    }
    private static final int RUSAGE_CHILDREN = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define RUSAGE_CHILDREN -1
     * }
     */
    public static int RUSAGE_CHILDREN() {
        return RUSAGE_CHILDREN;
    }
    private static final int RUSAGE_INFO_CURRENT = (int)6L;
    /**
     * {@snippet lang=c :
     * #define RUSAGE_INFO_CURRENT 6
     * }
     */
    public static int RUSAGE_INFO_CURRENT() {
        return RUSAGE_INFO_CURRENT;
    }
    private static final long RLIM_INFINITY = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define RLIM_INFINITY 9223372036854775807
     * }
     */
    public static long RLIM_INFINITY() {
        return RLIM_INFINITY;
    }
    private static final long RLIM_SAVED_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define RLIM_SAVED_MAX 9223372036854775807
     * }
     */
    public static long RLIM_SAVED_MAX() {
        return RLIM_SAVED_MAX;
    }
    private static final long RLIM_SAVED_CUR = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define RLIM_SAVED_CUR 9223372036854775807
     * }
     */
    public static long RLIM_SAVED_CUR() {
        return RLIM_SAVED_CUR;
    }
    private static final int RLIMIT_RSS = (int)5L;
    /**
     * {@snippet lang=c :
     * #define RLIMIT_RSS 5
     * }
     */
    public static int RLIMIT_RSS() {
        return RLIMIT_RSS;
    }
    private static final int IOPOL_APPLICATION = (int)5L;
    /**
     * {@snippet lang=c :
     * #define IOPOL_APPLICATION 5
     * }
     */
    public static int IOPOL_APPLICATION() {
        return IOPOL_APPLICATION;
    }
    private static final int IOPOL_NORMAL = (int)1L;
    /**
     * {@snippet lang=c :
     * #define IOPOL_NORMAL 1
     * }
     */
    public static int IOPOL_NORMAL() {
        return IOPOL_NORMAL;
    }
    private static final int WAIT_ANY = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define WAIT_ANY -1
     * }
     */
    public static int WAIT_ANY() {
        return WAIT_ANY;
    }
    private static final int MACH_PORT_DEAD = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_DEAD 4294967295
     * }
     */
    public static int MACH_PORT_DEAD() {
        return MACH_PORT_DEAD;
    }
    private static final int MACH_PORT_RIGHT_SEND = (int)0L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_RIGHT_SEND 0
     * }
     */
    public static int MACH_PORT_RIGHT_SEND() {
        return MACH_PORT_RIGHT_SEND;
    }
    private static final int MACH_PORT_RIGHT_RECEIVE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_RIGHT_RECEIVE 1
     * }
     */
    public static int MACH_PORT_RIGHT_RECEIVE() {
        return MACH_PORT_RIGHT_RECEIVE;
    }
    private static final int MACH_PORT_RIGHT_SEND_ONCE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_RIGHT_SEND_ONCE 2
     * }
     */
    public static int MACH_PORT_RIGHT_SEND_ONCE() {
        return MACH_PORT_RIGHT_SEND_ONCE;
    }
    private static final int MACH_PORT_RIGHT_PORT_SET = (int)3L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_RIGHT_PORT_SET 3
     * }
     */
    public static int MACH_PORT_RIGHT_PORT_SET() {
        return MACH_PORT_RIGHT_PORT_SET;
    }
    private static final int MACH_PORT_RIGHT_DEAD_NAME = (int)4L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_RIGHT_DEAD_NAME 4
     * }
     */
    public static int MACH_PORT_RIGHT_DEAD_NAME() {
        return MACH_PORT_RIGHT_DEAD_NAME;
    }
    private static final int MACH_PORT_RIGHT_LABELH = (int)5L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_RIGHT_LABELH 5
     * }
     */
    public static int MACH_PORT_RIGHT_LABELH() {
        return MACH_PORT_RIGHT_LABELH;
    }
    private static final int MACH_PORT_RIGHT_NUMBER = (int)6L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_RIGHT_NUMBER 6
     * }
     */
    public static int MACH_PORT_RIGHT_NUMBER() {
        return MACH_PORT_RIGHT_NUMBER;
    }
    private static final int MACH_PORT_TYPE_NONE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_TYPE_NONE 0
     * }
     */
    public static int MACH_PORT_TYPE_NONE() {
        return MACH_PORT_TYPE_NONE;
    }
    private static final int MACH_PORT_TYPE_SEND = (int)65536L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_TYPE_SEND 65536
     * }
     */
    public static int MACH_PORT_TYPE_SEND() {
        return MACH_PORT_TYPE_SEND;
    }
    private static final int MACH_PORT_TYPE_RECEIVE = (int)131072L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_TYPE_RECEIVE 131072
     * }
     */
    public static int MACH_PORT_TYPE_RECEIVE() {
        return MACH_PORT_TYPE_RECEIVE;
    }
    private static final int MACH_PORT_TYPE_SEND_ONCE = (int)262144L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_TYPE_SEND_ONCE 262144
     * }
     */
    public static int MACH_PORT_TYPE_SEND_ONCE() {
        return MACH_PORT_TYPE_SEND_ONCE;
    }
    private static final int MACH_PORT_TYPE_PORT_SET = (int)524288L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_TYPE_PORT_SET 524288
     * }
     */
    public static int MACH_PORT_TYPE_PORT_SET() {
        return MACH_PORT_TYPE_PORT_SET;
    }
    private static final int MACH_PORT_TYPE_DEAD_NAME = (int)1048576L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_TYPE_DEAD_NAME 1048576
     * }
     */
    public static int MACH_PORT_TYPE_DEAD_NAME() {
        return MACH_PORT_TYPE_DEAD_NAME;
    }
    private static final int MACH_PORT_TYPE_LABELH = (int)2097152L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_TYPE_LABELH 2097152
     * }
     */
    public static int MACH_PORT_TYPE_LABELH() {
        return MACH_PORT_TYPE_LABELH;
    }
    private static final int MACH_PORT_TYPE_SEND_RECEIVE = (int)196608L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_TYPE_SEND_RECEIVE 196608
     * }
     */
    public static int MACH_PORT_TYPE_SEND_RECEIVE() {
        return MACH_PORT_TYPE_SEND_RECEIVE;
    }
    private static final int MACH_PORT_TYPE_SEND_RIGHTS = (int)327680L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_TYPE_SEND_RIGHTS 327680
     * }
     */
    public static int MACH_PORT_TYPE_SEND_RIGHTS() {
        return MACH_PORT_TYPE_SEND_RIGHTS;
    }
    private static final int MACH_PORT_TYPE_PORT_RIGHTS = (int)458752L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_TYPE_PORT_RIGHTS 458752
     * }
     */
    public static int MACH_PORT_TYPE_PORT_RIGHTS() {
        return MACH_PORT_TYPE_PORT_RIGHTS;
    }
    private static final int MACH_PORT_TYPE_PORT_OR_DEAD = (int)1507328L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_TYPE_PORT_OR_DEAD 1507328
     * }
     */
    public static int MACH_PORT_TYPE_PORT_OR_DEAD() {
        return MACH_PORT_TYPE_PORT_OR_DEAD;
    }
    private static final int MACH_PORT_TYPE_ALL_RIGHTS = (int)2031616L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_TYPE_ALL_RIGHTS 2031616
     * }
     */
    public static int MACH_PORT_TYPE_ALL_RIGHTS() {
        return MACH_PORT_TYPE_ALL_RIGHTS;
    }
    private static final int MACH_PORT_TYPE_DNREQUEST = (int)2147483648L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_TYPE_DNREQUEST 2147483648
     * }
     */
    public static int MACH_PORT_TYPE_DNREQUEST() {
        return MACH_PORT_TYPE_DNREQUEST;
    }
    private static final int MACH_PORT_QLIMIT_ZERO = (int)0L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_QLIMIT_ZERO 0
     * }
     */
    public static int MACH_PORT_QLIMIT_ZERO() {
        return MACH_PORT_QLIMIT_ZERO;
    }
    private static final int MACH_PORT_QLIMIT_BASIC = (int)5L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_QLIMIT_BASIC 5
     * }
     */
    public static int MACH_PORT_QLIMIT_BASIC() {
        return MACH_PORT_QLIMIT_BASIC;
    }
    private static final int MACH_PORT_QLIMIT_SMALL = (int)16L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_QLIMIT_SMALL 16
     * }
     */
    public static int MACH_PORT_QLIMIT_SMALL() {
        return MACH_PORT_QLIMIT_SMALL;
    }
    private static final int MACH_PORT_QLIMIT_LARGE = (int)1024L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_QLIMIT_LARGE 1024
     * }
     */
    public static int MACH_PORT_QLIMIT_LARGE() {
        return MACH_PORT_QLIMIT_LARGE;
    }
    private static final int MACH_PORT_QLIMIT_KERNEL = (int)65534L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_QLIMIT_KERNEL 65534
     * }
     */
    public static int MACH_PORT_QLIMIT_KERNEL() {
        return MACH_PORT_QLIMIT_KERNEL;
    }
    private static final int MACH_PORT_QLIMIT_MIN = (int)0L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_QLIMIT_MIN 0
     * }
     */
    public static int MACH_PORT_QLIMIT_MIN() {
        return MACH_PORT_QLIMIT_MIN;
    }
    private static final int MACH_PORT_QLIMIT_DEFAULT = (int)5L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_QLIMIT_DEFAULT 5
     * }
     */
    public static int MACH_PORT_QLIMIT_DEFAULT() {
        return MACH_PORT_QLIMIT_DEFAULT;
    }
    private static final int MACH_PORT_QLIMIT_MAX = (int)1024L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_QLIMIT_MAX 1024
     * }
     */
    public static int MACH_PORT_QLIMIT_MAX() {
        return MACH_PORT_QLIMIT_MAX;
    }
    private static final int MACH_PORT_LIMITS_INFO_COUNT = (int)1L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_LIMITS_INFO_COUNT 1
     * }
     */
    public static int MACH_PORT_LIMITS_INFO_COUNT() {
        return MACH_PORT_LIMITS_INFO_COUNT;
    }
    private static final int MACH_PORT_RECEIVE_STATUS_COUNT = (int)10L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_RECEIVE_STATUS_COUNT 10
     * }
     */
    public static int MACH_PORT_RECEIVE_STATUS_COUNT() {
        return MACH_PORT_RECEIVE_STATUS_COUNT;
    }
    private static final int MACH_PORT_INFO_EXT_COUNT = (int)17L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_INFO_EXT_COUNT 17
     * }
     */
    public static int MACH_PORT_INFO_EXT_COUNT() {
        return MACH_PORT_INFO_EXT_COUNT;
    }
    private static final int MACH_PORT_GUARD_INFO_COUNT = (int)2L;
    /**
     * {@snippet lang=c :
     * #define MACH_PORT_GUARD_INFO_COUNT 2
     * }
     */
    public static int MACH_PORT_GUARD_INFO_COUNT() {
        return MACH_PORT_GUARD_INFO_COUNT;
    }
    private static final byte MACH_SERVICE_PORT_INFO_COUNT = (byte)0L;
    /**
     * {@snippet lang=c :
     * #define MACH_SERVICE_PORT_INFO_COUNT 0
     * }
     */
    public static byte MACH_SERVICE_PORT_INFO_COUNT() {
        return MACH_SERVICE_PORT_INFO_COUNT;
    }
    private static final int MAX_FATAL_kGUARD_EXC_CODE = (int)128L;
    /**
     * {@snippet lang=c :
     * #define MAX_FATAL_kGUARD_EXC_CODE 128
     * }
     */
    public static int MAX_FATAL_kGUARD_EXC_CODE() {
        return MAX_FATAL_kGUARD_EXC_CODE;
    }
    private static final long MPG_FLAGS_NONE = 0L;
    /**
     * {@snippet lang=c :
     * #define MPG_FLAGS_NONE 0
     * }
     */
    public static long MPG_FLAGS_NONE() {
        return MPG_FLAGS_NONE;
    }
    private static final int MAX_OPTIONAL_kGUARD_EXC_CODE = (int)524288L;
    /**
     * {@snippet lang=c :
     * #define MAX_OPTIONAL_kGUARD_EXC_CODE 524288
     * }
     */
    public static int MAX_OPTIONAL_kGUARD_EXC_CODE() {
        return MAX_OPTIONAL_kGUARD_EXC_CODE;
    }
    private static final long MPG_FLAGS_STRICT_REPLY_INVALID_REPLY_DISP = 72057594037927936L;
    /**
     * {@snippet lang=c :
     * #define MPG_FLAGS_STRICT_REPLY_INVALID_REPLY_DISP 72057594037927936
     * }
     */
    public static long MPG_FLAGS_STRICT_REPLY_INVALID_REPLY_DISP() {
        return MPG_FLAGS_STRICT_REPLY_INVALID_REPLY_DISP;
    }
    private static final long MPG_FLAGS_STRICT_REPLY_INVALID_REPLY_PORT = 144115188075855872L;
    /**
     * {@snippet lang=c :
     * #define MPG_FLAGS_STRICT_REPLY_INVALID_REPLY_PORT 144115188075855872
     * }
     */
    public static long MPG_FLAGS_STRICT_REPLY_INVALID_REPLY_PORT() {
        return MPG_FLAGS_STRICT_REPLY_INVALID_REPLY_PORT;
    }
    private static final long MPG_FLAGS_STRICT_REPLY_INVALID_VOUCHER = 288230376151711744L;
    /**
     * {@snippet lang=c :
     * #define MPG_FLAGS_STRICT_REPLY_INVALID_VOUCHER 288230376151711744
     * }
     */
    public static long MPG_FLAGS_STRICT_REPLY_INVALID_VOUCHER() {
        return MPG_FLAGS_STRICT_REPLY_INVALID_VOUCHER;
    }
    private static final long MPG_FLAGS_STRICT_REPLY_NO_BANK_ATTR = 576460752303423488L;
    /**
     * {@snippet lang=c :
     * #define MPG_FLAGS_STRICT_REPLY_NO_BANK_ATTR 576460752303423488
     * }
     */
    public static long MPG_FLAGS_STRICT_REPLY_NO_BANK_ATTR() {
        return MPG_FLAGS_STRICT_REPLY_NO_BANK_ATTR;
    }
    private static final long MPG_FLAGS_STRICT_REPLY_MISMATCHED_PERSONA = 1152921504606846976L;
    /**
     * {@snippet lang=c :
     * #define MPG_FLAGS_STRICT_REPLY_MISMATCHED_PERSONA 1152921504606846976
     * }
     */
    public static long MPG_FLAGS_STRICT_REPLY_MISMATCHED_PERSONA() {
        return MPG_FLAGS_STRICT_REPLY_MISMATCHED_PERSONA;
    }
    private static final long MPG_FLAGS_STRICT_REPLY_MASK = -72057594037927936L;
    /**
     * {@snippet lang=c :
     * #define MPG_FLAGS_STRICT_REPLY_MASK -72057594037927936
     * }
     */
    public static long MPG_FLAGS_STRICT_REPLY_MASK() {
        return MPG_FLAGS_STRICT_REPLY_MASK;
    }
    private static final long MPG_FLAGS_MOD_REFS_PINNED_DEALLOC = 72057594037927936L;
    /**
     * {@snippet lang=c :
     * #define MPG_FLAGS_MOD_REFS_PINNED_DEALLOC 72057594037927936
     * }
     */
    public static long MPG_FLAGS_MOD_REFS_PINNED_DEALLOC() {
        return MPG_FLAGS_MOD_REFS_PINNED_DEALLOC;
    }
    private static final long MPG_FLAGS_MOD_REFS_PINNED_DESTROY = 144115188075855872L;
    /**
     * {@snippet lang=c :
     * #define MPG_FLAGS_MOD_REFS_PINNED_DESTROY 144115188075855872
     * }
     */
    public static long MPG_FLAGS_MOD_REFS_PINNED_DESTROY() {
        return MPG_FLAGS_MOD_REFS_PINNED_DESTROY;
    }
    private static final long MPG_FLAGS_MOD_REFS_PINNED_COPYIN = 288230376151711744L;
    /**
     * {@snippet lang=c :
     * #define MPG_FLAGS_MOD_REFS_PINNED_COPYIN 288230376151711744
     * }
     */
    public static long MPG_FLAGS_MOD_REFS_PINNED_COPYIN() {
        return MPG_FLAGS_MOD_REFS_PINNED_COPYIN;
    }
    private static final long MPG_FLAGS_IMMOVABLE_PINNED = 72057594037927936L;
    /**
     * {@snippet lang=c :
     * #define MPG_FLAGS_IMMOVABLE_PINNED 72057594037927936
     * }
     */
    public static long MPG_FLAGS_IMMOVABLE_PINNED() {
        return MPG_FLAGS_IMMOVABLE_PINNED;
    }
    private static final int TIME_MICROS_MAX = (int)1000000L;
    /**
     * {@snippet lang=c :
     * #define TIME_MICROS_MAX 1000000
     * }
     */
    public static int TIME_MICROS_MAX() {
        return TIME_MICROS_MAX;
    }
    private static final long NSEC_PER_USEC = 1000L;
    /**
     * {@snippet lang=c :
     * #define NSEC_PER_USEC 1000
     * }
     */
    public static long NSEC_PER_USEC() {
        return NSEC_PER_USEC;
    }
    private static final long USEC_PER_SEC = 1000000L;
    /**
     * {@snippet lang=c :
     * #define USEC_PER_SEC 1000000
     * }
     */
    public static long USEC_PER_SEC() {
        return USEC_PER_SEC;
    }
    private static final long NSEC_PER_SEC = 1000000000L;
    /**
     * {@snippet lang=c :
     * #define NSEC_PER_SEC 1000000000
     * }
     */
    public static long NSEC_PER_SEC() {
        return NSEC_PER_SEC;
    }
    private static final long NSEC_PER_MSEC = 1000000L;
    /**
     * {@snippet lang=c :
     * #define NSEC_PER_MSEC 1000000
     * }
     */
    public static long NSEC_PER_MSEC() {
        return NSEC_PER_MSEC;
    }
    private static final long MSEC_PER_SEC = 1000L;
    /**
     * {@snippet lang=c :
     * #define MSEC_PER_SEC 1000
     * }
     */
    public static long MSEC_PER_SEC() {
        return MSEC_PER_SEC;
    }
    private static final long DISPATCH_TIME_NOW = 0L;
    /**
     * {@snippet lang=c :
     * #define DISPATCH_TIME_NOW 0
     * }
     */
    public static long DISPATCH_TIME_NOW() {
        return DISPATCH_TIME_NOW;
    }
    private static final long DISPATCH_TIME_FOREVER = -1L;
    /**
     * {@snippet lang=c :
     * #define DISPATCH_TIME_FOREVER -1
     * }
     */
    public static long DISPATCH_TIME_FOREVER() {
        return DISPATCH_TIME_FOREVER;
    }
    private static final int QOS_MIN_RELATIVE_PRIORITY = (int)-15L;
    /**
     * {@snippet lang=c :
     * #define QOS_MIN_RELATIVE_PRIORITY -15
     * }
     */
    public static int QOS_MIN_RELATIVE_PRIORITY() {
        return QOS_MIN_RELATIVE_PRIORITY;
    }
    private static final int DISPATCH_QUEUE_PRIORITY_LOW = (int)-2L;
    /**
     * {@snippet lang=c :
     * #define DISPATCH_QUEUE_PRIORITY_LOW -2
     * }
     */
    public static int DISPATCH_QUEUE_PRIORITY_LOW() {
        return DISPATCH_QUEUE_PRIORITY_LOW;
    }
    private static final int DISPATCH_QUEUE_PRIORITY_BACKGROUND = (int)-32768L;
    /**
     * {@snippet lang=c :
     * #define DISPATCH_QUEUE_PRIORITY_BACKGROUND -32768
     * }
     */
    public static int DISPATCH_QUEUE_PRIORITY_BACKGROUND() {
        return DISPATCH_QUEUE_PRIORITY_BACKGROUND;
    }
    private static final MemorySegment DISPATCH_QUEUE_SERIAL = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define DISPATCH_QUEUE_SERIAL (void*) 0
     * }
     */
    public static MemorySegment DISPATCH_QUEUE_SERIAL() {
        return DISPATCH_QUEUE_SERIAL;
    }
    private static final MemorySegment DISPATCH_TARGET_QUEUE_DEFAULT = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define DISPATCH_TARGET_QUEUE_DEFAULT (void*) 0
     * }
     */
    public static MemorySegment DISPATCH_TARGET_QUEUE_DEFAULT() {
        return DISPATCH_TARGET_QUEUE_DEFAULT;
    }
    private static final MemorySegment DISPATCH_CURRENT_QUEUE_LABEL = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define DISPATCH_CURRENT_QUEUE_LABEL (void*) 0
     * }
     */
    public static MemorySegment DISPATCH_CURRENT_QUEUE_LABEL() {
        return DISPATCH_CURRENT_QUEUE_LABEL;
    }
    private static final int CLK_TCK = (int)100L;
    /**
     * {@snippet lang=c :
     * #define CLK_TCK 100
     * }
     */
    public static int CLK_TCK() {
        return CLK_TCK;
    }
    private static final int SCHAR_MIN = (int)-128L;
    /**
     * {@snippet lang=c :
     * #define SCHAR_MIN -128
     * }
     */
    public static int SCHAR_MIN() {
        return SCHAR_MIN;
    }
    private static final int CHAR_MIN = (int)-128L;
    /**
     * {@snippet lang=c :
     * #define CHAR_MIN -128
     * }
     */
    public static int CHAR_MIN() {
        return CHAR_MIN;
    }
    private static final int SHRT_MIN = (int)-32768L;
    /**
     * {@snippet lang=c :
     * #define SHRT_MIN -32768
     * }
     */
    public static int SHRT_MIN() {
        return SHRT_MIN;
    }
    private static final int UINT_MAX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define UINT_MAX 4294967295
     * }
     */
    public static int UINT_MAX() {
        return UINT_MAX;
    }
    private static final int INT_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define INT_MIN -2147483648
     * }
     */
    public static int INT_MIN() {
        return INT_MIN;
    }
    private static final long ULONG_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define ULONG_MAX -1
     * }
     */
    public static long ULONG_MAX() {
        return ULONG_MAX;
    }
    private static final long LONG_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define LONG_MAX 9223372036854775807
     * }
     */
    public static long LONG_MAX() {
        return LONG_MAX;
    }
    private static final long LONG_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define LONG_MIN -9223372036854775808
     * }
     */
    public static long LONG_MIN() {
        return LONG_MIN;
    }
    private static final long ULLONG_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define ULLONG_MAX -1
     * }
     */
    public static long ULLONG_MAX() {
        return ULLONG_MAX;
    }
    private static final long LLONG_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define LLONG_MAX 9223372036854775807
     * }
     */
    public static long LLONG_MAX() {
        return LLONG_MAX;
    }
    private static final long LLONG_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define LLONG_MIN -9223372036854775808
     * }
     */
    public static long LLONG_MIN() {
        return LLONG_MIN;
    }
    private static final long SSIZE_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define SSIZE_MAX 9223372036854775807
     * }
     */
    public static long SSIZE_MAX() {
        return SSIZE_MAX;
    }
    private static final long SIZE_T_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define SIZE_T_MAX -1
     * }
     */
    public static long SIZE_T_MAX() {
        return SIZE_T_MAX;
    }
    private static final long UQUAD_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UQUAD_MAX -1
     * }
     */
    public static long UQUAD_MAX() {
        return UQUAD_MAX;
    }
    private static final long QUAD_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define QUAD_MAX 9223372036854775807
     * }
     */
    public static long QUAD_MAX() {
        return QUAD_MAX;
    }
    private static final long QUAD_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define QUAD_MIN -9223372036854775808
     * }
     */
    public static long QUAD_MIN() {
        return QUAD_MIN;
    }
    private static final int MACH_MSG_TIMEOUT_NONE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_TIMEOUT_NONE 0
     * }
     */
    public static int MACH_MSG_TIMEOUT_NONE() {
        return MACH_MSG_TIMEOUT_NONE;
    }
    private static final int MACH_MSGH_BITS_PORTS_MASK = (int)2039583L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSGH_BITS_PORTS_MASK 2039583
     * }
     */
    public static int MACH_MSGH_BITS_PORTS_MASK() {
        return MACH_MSGH_BITS_PORTS_MASK;
    }
    private static final int MACH_MSGH_BITS_COMPLEX = (int)2147483648L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSGH_BITS_COMPLEX 2147483648
     * }
     */
    public static int MACH_MSGH_BITS_COMPLEX() {
        return MACH_MSGH_BITS_COMPLEX;
    }
    private static final int MACH_MSGH_BITS_USER = (int)2149523231L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSGH_BITS_USER 2149523231
     * }
     */
    public static int MACH_MSGH_BITS_USER() {
        return MACH_MSGH_BITS_USER;
    }
    private static final int MACH_MSGH_BITS_RAISEIMP = (int)536870912L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSGH_BITS_RAISEIMP 536870912
     * }
     */
    public static int MACH_MSGH_BITS_RAISEIMP() {
        return MACH_MSGH_BITS_RAISEIMP;
    }
    private static final int MACH_MSGH_BITS_DENAP = (int)536870912L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSGH_BITS_DENAP 536870912
     * }
     */
    public static int MACH_MSGH_BITS_DENAP() {
        return MACH_MSGH_BITS_DENAP;
    }
    private static final int MACH_MSGH_BITS_IMPHOLDASRT = (int)268435456L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSGH_BITS_IMPHOLDASRT 268435456
     * }
     */
    public static int MACH_MSGH_BITS_IMPHOLDASRT() {
        return MACH_MSGH_BITS_IMPHOLDASRT;
    }
    private static final int MACH_MSGH_BITS_DENAPHOLDASRT = (int)268435456L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSGH_BITS_DENAPHOLDASRT 268435456
     * }
     */
    public static int MACH_MSGH_BITS_DENAPHOLDASRT() {
        return MACH_MSGH_BITS_DENAPHOLDASRT;
    }
    private static final int MACH_MSGH_BITS_CIRCULAR = (int)268435456L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSGH_BITS_CIRCULAR 268435456
     * }
     */
    public static int MACH_MSGH_BITS_CIRCULAR() {
        return MACH_MSGH_BITS_CIRCULAR;
    }
    private static final int MACH_MSGH_BITS_USED = (int)2954829599L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSGH_BITS_USED 2954829599
     * }
     */
    public static int MACH_MSGH_BITS_USED() {
        return MACH_MSGH_BITS_USED;
    }
    private static final MemorySegment MACH_MSG_SIZE_NULL = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_SIZE_NULL (void*) 0
     * }
     */
    public static MemorySegment MACH_MSG_SIZE_NULL() {
        return MACH_MSG_SIZE_NULL;
    }
    private static final int MACH_MSG_PRIORITY_UNSPECIFIED = (int)0L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_PRIORITY_UNSPECIFIED 0
     * }
     */
    public static int MACH_MSG_PRIORITY_UNSPECIFIED() {
        return MACH_MSG_PRIORITY_UNSPECIFIED;
    }
    private static final int MACH_MSG_DESCRIPTOR_MAX = (int)4L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_DESCRIPTOR_MAX 4
     * }
     */
    public static int MACH_MSG_DESCRIPTOR_MAX() {
        return MACH_MSG_DESCRIPTOR_MAX;
    }
    private static final MemorySegment MACH_MSG_BODY_NULL = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_BODY_NULL (void*) 0
     * }
     */
    public static MemorySegment MACH_MSG_BODY_NULL() {
        return MACH_MSG_BODY_NULL;
    }
    private static final MemorySegment MACH_MSG_DESCRIPTOR_NULL = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_DESCRIPTOR_NULL (void*) 0
     * }
     */
    public static MemorySegment MACH_MSG_DESCRIPTOR_NULL() {
        return MACH_MSG_DESCRIPTOR_NULL;
    }
    private static final MemorySegment MACH_MSG_NULL = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_NULL (void*) 0
     * }
     */
    public static MemorySegment MACH_MSG_NULL() {
        return MACH_MSG_NULL;
    }
    private static final int MACH_MSG_FILTER_POLICY_ALLOW = (int)0L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_FILTER_POLICY_ALLOW 0
     * }
     */
    public static int MACH_MSG_FILTER_POLICY_ALLOW() {
        return MACH_MSG_FILTER_POLICY_ALLOW;
    }
    private static final long MACH_MSG_TRAILER_MINIMUM_SIZE = 8L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_TRAILER_MINIMUM_SIZE 8
     * }
     */
    public static long MACH_MSG_TRAILER_MINIMUM_SIZE() {
        return MACH_MSG_TRAILER_MINIMUM_SIZE;
    }
    private static final int MAX_TRAILER_SIZE = (int)68L;
    /**
     * {@snippet lang=c :
     * #define MAX_TRAILER_SIZE 68
     * }
     */
    public static int MAX_TRAILER_SIZE() {
        return MAX_TRAILER_SIZE;
    }
    private static final long MACH_MSG_TRAILER_FORMAT_0_SIZE = 20L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_TRAILER_FORMAT_0_SIZE 20
     * }
     */
    public static long MACH_MSG_TRAILER_FORMAT_0_SIZE() {
        return MACH_MSG_TRAILER_FORMAT_0_SIZE;
    }
    private static final int MACH_MSG_SIZE_MAX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_SIZE_MAX 4294967295
     * }
     */
    public static int MACH_MSG_SIZE_MAX() {
        return MACH_MSG_SIZE_MAX;
    }
    private static final int MACH_MSG_SIZE_RELIABLE = (int)262144L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_SIZE_RELIABLE 262144
     * }
     */
    public static int MACH_MSG_SIZE_RELIABLE() {
        return MACH_MSG_SIZE_RELIABLE;
    }
    private static final int MACH_MSG_TYPE_PORT_RECEIVE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_TYPE_PORT_RECEIVE 16
     * }
     */
    public static int MACH_MSG_TYPE_PORT_RECEIVE() {
        return MACH_MSG_TYPE_PORT_RECEIVE;
    }
    private static final int MACH_MSG_TYPE_PORT_SEND = (int)17L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_TYPE_PORT_SEND 17
     * }
     */
    public static int MACH_MSG_TYPE_PORT_SEND() {
        return MACH_MSG_TYPE_PORT_SEND;
    }
    private static final int MACH_MSG_TYPE_PORT_SEND_ONCE = (int)18L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_TYPE_PORT_SEND_ONCE 18
     * }
     */
    public static int MACH_MSG_TYPE_PORT_SEND_ONCE() {
        return MACH_MSG_TYPE_PORT_SEND_ONCE;
    }
    private static final int MACH_MSG_TYPE_POLYMORPHIC = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define MACH_MSG_TYPE_POLYMORPHIC 4294967295
     * }
     */
    public static int MACH_MSG_TYPE_POLYMORPHIC() {
        return MACH_MSG_TYPE_POLYMORPHIC;
    }
    private static final int MACH_SEND_NODENAP = (int)262144L;
    /**
     * {@snippet lang=c :
     * #define MACH_SEND_NODENAP 262144
     * }
     */
    public static int MACH_SEND_NODENAP() {
        return MACH_SEND_NODENAP;
    }
    private static final int MACH_SEND_SYNC_USE_THRPRI = (int)2097152L;
    /**
     * {@snippet lang=c :
     * #define MACH_SEND_SYNC_USE_THRPRI 2097152
     * }
     */
    public static int MACH_SEND_SYNC_USE_THRPRI() {
        return MACH_SEND_SYNC_USE_THRPRI;
    }
    private static final int MACH_RCV_TRAILER_MASK = (int)251658240L;
    /**
     * {@snippet lang=c :
     * #define MACH_RCV_TRAILER_MASK 251658240
     * }
     */
    public static int MACH_RCV_TRAILER_MASK() {
        return MACH_RCV_TRAILER_MASK;
    }
    private static final int DISPATCH_PROC_EXIT = (int)2147483648L;
    /**
     * {@snippet lang=c :
     * #define DISPATCH_PROC_EXIT 2147483648
     * }
     */
    public static int DISPATCH_PROC_EXIT() {
        return DISPATCH_PROC_EXIT;
    }
    private static final MemorySegment DISPATCH_DATA_DESTRUCTOR_DEFAULT = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define DISPATCH_DATA_DESTRUCTOR_DEFAULT (void*) 0
     * }
     */
    public static MemorySegment DISPATCH_DATA_DESTRUCTOR_DEFAULT() {
        return DISPATCH_DATA_DESTRUCTOR_DEFAULT;
    }
    private static final int CL_IMAGE_2D = (int)4337L;
    /**
     * {@snippet lang=c :
     * #define CL_IMAGE_2D 4337
     * }
     */
    public static int CL_IMAGE_2D() {
        return CL_IMAGE_2D;
    }
    private static final int CL_IMAGE_3D = (int)4338L;
    /**
     * {@snippet lang=c :
     * #define CL_IMAGE_3D 4338
     * }
     */
    public static int CL_IMAGE_3D() {
        return CL_IMAGE_3D;
    }
    private static final long CL_DISPATCH_QUEUE_PRIORITY_DEFAULT = 576460752303423488L;
    /**
     * {@snippet lang=c :
     * #define CL_DISPATCH_QUEUE_PRIORITY_DEFAULT 576460752303423488
     * }
     */
    public static long CL_DISPATCH_QUEUE_PRIORITY_DEFAULT() {
        return CL_DISPATCH_QUEUE_PRIORITY_DEFAULT;
    }
    private static final long CL_DISPATCH_QUEUE_PRIORITY_BACKGROUND = 1152921504606846976L;
    /**
     * {@snippet lang=c :
     * #define CL_DISPATCH_QUEUE_PRIORITY_BACKGROUND 1152921504606846976
     * }
     */
    public static long CL_DISPATCH_QUEUE_PRIORITY_BACKGROUND() {
        return CL_DISPATCH_QUEUE_PRIORITY_BACKGROUND;
    }
    private static final long CL_DISPATCH_QUEUE_PRIORITY_HIGH = 4611686018427387904L;
    /**
     * {@snippet lang=c :
     * #define CL_DISPATCH_QUEUE_PRIORITY_HIGH 4611686018427387904
     * }
     */
    public static long CL_DISPATCH_QUEUE_PRIORITY_HIGH() {
        return CL_DISPATCH_QUEUE_PRIORITY_HIGH;
    }
    private static final long CL_DISPATCH_QUEUE_PRIORITY_LOW = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define CL_DISPATCH_QUEUE_PRIORITY_LOW -9223372036854775808
     * }
     */
    public static long CL_DISPATCH_QUEUE_PRIORITY_LOW() {
        return CL_DISPATCH_QUEUE_PRIORITY_LOW;
    }
    private static final long CL_DEVICE_TYPE_USE_ID = 2305843009213693952L;
    /**
     * {@snippet lang=c :
     * #define CL_DEVICE_TYPE_USE_ID 2305843009213693952
     * }
     */
    public static long CL_DEVICE_TYPE_USE_ID() {
        return CL_DEVICE_TYPE_USE_ID;
    }
}

