// Generated by jextract

package opencl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct os_workgroup_join_token_opaque_s {
 *     uint32_t sig;
 *     char opaque[36];
 * } os_workgroup_join_token_s
 * }
 */
public class os_workgroup_join_token_s extends os_workgroup_join_token_opaque_s {

    os_workgroup_join_token_s() {
        // Should not be called directly
    }
}

